### ISSUE TITLE
Example program cannot connect in Centos7 VM

### ISSUE THREAD

**Issue by rigdent** [phsym/sctp-sys#1]
Hello,

I was unsure where else to put this so I am putting it here.

I was unable to get your example file to run properly. This is on a centos 7 vm and lksctp-tools were installed through yum. The program compiles fine but fails on connect line here
https://github.com/phsym/sctp-sys/blob/master/examples/dirty.rs#L33

If you have any advice or comments, it would be appreciated. Thanks!

**Comment by phsym** [comment]
Hi,

Do you have a sctp enpoint listenning on 127.0.0.1:3868 ? If not, you can create one with netcat.

**Comment by rigdent** [comment]
Oh I didn't. Thanks! I actually ended up deciding not to use it, so I'm going to close the issue. Thanks still!

**Comment by phsym** [comment]
You can have a look to https://github.com/phsym/rust-sctp if you need a higher level library. It's still quite basic for now, but do its job
